spring.application.name: user-service

spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://sarandy:sarandy@mongodb:27017/
      authentication-database: admin
      database: mongodb
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server:8888
    bus:
      refresh:
        enabled: true
      enabled: true
  kafka:
    bootstrap-servers: 34.101.242.30:9092
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus